apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: petclinic-gateway
  namespace: default
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: petclinic-gateway
      port: 80
  virtualhost:
    fqdn: petclinic.afewell-devcontainerdemo.tanzu.pro
    tls:
      secretName: taptlscert
