apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tds
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tds-repo
spec:
  fetch:
    imgpkgBundle:
      image: harbor.afewell-devcontainerdemo.tanzu.pro/library/tds-packages/tds-packages:1.12.0
